spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp:localhost/~/.order
    username: sa
    password: 1234

  jpa:
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create-drop

  h2:
    console:
      enabled: true

server:
  error:
    include-binding-errors: never
    include-exception: false
    include-message: never
    include-stacktrace: never